"""empty message

Revision ID: 318d32fb1e37
Revises: d0278b49d41f
Create Date: 2025-05-04 20:35:03.416734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318d32fb1e37'
down_revision = 'd0278b49d41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('game_id')
        batch_op.drop_index('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('title', ['title'], unique=True)
        batch_op.create_index('game_id', ['game_id'], unique=True)

    # ### end Alembic commands ###
