"""empty message

Revision ID: d0278b49d41f
Revises: 30f71962def3
Create Date: 2025-05-04 17:41:25.852144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0278b49d41f'
down_revision = '30f71962def3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('server', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('game_id', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('game_name', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint(None, ['game_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('game_name')
        batch_op.drop_column('game_id')
        batch_op.drop_column('server')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
